name: Canary release

on:
  push:
    branches:
      - next

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node-version: [
          12.x, # current LTS
          14.x # next LTS
        ]
    steps:
      # Checkout git branch
      - uses: actions/checkout@master
      # Install node.js environment
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      # Install dependencies
      - name: Install
        run: yarn install
      # Run all tests
      - name: Test
        run: yarn run test

  # Canary release with tag "next"
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@master
        with:
          # Fetch the entire history
          fetch-depth: 0
      # Install node.js environment
      - uses: actions/setup-node@v2-beta
        with:
          always-auth: true
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@flo-sch'
      # Authenticate NPM registry
      - name: Authenticate NPM registry
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm config set @flo-sch:registry https://registry.npmjs.org
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Install dependencies
      - name: Install
        run: yarn install
      # Build packages
      - name: Build
        run: yarn run build
      # Publish next tag
      - name: Publish next tag
        run: yarn lerna publish --canary --preid next --pre-dist-tag next --yes
