name: Test

on: pull_request

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node-version: [
          12.x, # current LTS
          14.x # next LTS
        ]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout git branch
      - uses: actions/checkout@master
      # Install node.js environment
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      # Install dependencies
      - name: Install
        run: yarn install
      # Run all tests
      - name: Test
        run: yarn run test

  # Simulate version release
  simulate:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - uses: actions/checkout@master
        with:
          # Fetch the entire history
          fetch-depth: 0
      # Install node.js environment
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      # Install dependencies
      - name: Install
        run: yarn install
      # Simulate lerna version
      - name: Simulate release version
        run: yarn lerna version --no-git-tag-version --no-push --allow-branch '**/*' --yes
